# Generated by Django 5.0.3 on 2024-04-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_evento_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(unique=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
