# Generated by Django 5.0.3 on 2024-04-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_diario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.IntegerField()),
                ('conteudo', models.TextField(blank=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='diario.diario')),
            ],
            options={
                'unique_together': {('diario', 'numero_pagina')},
            },
        ),
    ]
