# Generated by Django 5.0.3 on 2024-04-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_moodlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('numero_sessao', models.IntegerField()),
                ('avaliacao_humor', models.CharField(max_length=50)),
                ('mudancas_humor', models.TextField()),
                ('eventos_semana', models.TextField()),
                ('sintomas', models.JSONField()),
                ('estrategias_coping', models.JSONField()),
                ('observacoes_terapeuta', models.TextField()),
                ('objetivos_proxima_semana', models.TextField()),
            ],
        ),
    ]
