# Generated by Django 5.0.4 on 2024-05-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='pagina',
            name='_conteudo',
            field=models.TextField(blank=True, db_column='conteudo'),
        ),
    ]
