# Generated by Django 5.0.4 on 2024-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0014_remove_pagina__conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
    ]
